//
// Created by sebas on 10/15/25.
//

#ifndef ENSEA_ALGO_TP1_GENERIC_CONSTANTS_H
#define ENSEA_ALGO_TP1_GENERIC_CONSTANTS_H

#define MAX_STACK_ARRAY_SIZE 4096
#define STACK_UNDERFLOW_DEFAULT_VALUE 0

#endif //ENSEA_ALGO_TP1_GENERIC_CONSTANTS_H